-- Create admin user
INSERT INTO
  auth.users (
    instance_id,
    id,
    aud,
    role,
    email,
    encrypted_password,
    email_confirmed_at,
    invited_at,
    confirmation_token,
    confirmation_sent_at,
    recovery_token,
    recovery_sent_at,
    email_change_token_new,
    email_change,
    email_change_sent_at,
    last_sign_in_at,
    raw_app_meta_data,
    raw_user_meta_data,
    is_super_admin,
    created_at,
    updated_at,
    phone,
    phone_confirmed_at,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    email_change_token_current,
    email_change_confirm_status,
    banned_until,
    reauthentication_token,
    reauthentication_sent_at
  )
VALUES
  (
    '00000000-0000-0000-0000-000000000000',
    'e1c67c93-1c84-4d4d-a5da-c2227879c690',
    'authenticated',
    'authenticated',
    'iam@dallastjames.dev',
    '$2a$10$X0jKcnWDivwu3H1IadHWb.4sUBt0ZU2whgjYk6kUWJXc7./WZmWL.',
    '2022-12-02 18:39:26.434692+00',
    NULL,
    '',
    NULL,
    '',
    NULL,
    '',
    '',
    NULL,
    NULL,
    '{"provider": "email", "providers": ["email"]}',
    '{"username": "admin"}',
    NULL,
    '2022-12-02 18:39:26.424829+00',
    '2022-12-02 18:39:26.442437+00',
    NULL,
    NULL,
    '',
    '',
    NULL,
    '',
    0,
    NULL,
    '',
    NULL
  );